---
name: "Environment"
rule_text: |
  Environment is an encounter card type that creates an
  overarching rule or set of rules for the scenario.
  An environment card enters play next to the villain, and is
  active so long as it remains in play.
  â€¢ If an environment enters play, it remains in play until a
  card ability or game effect causes it to leave play.
